[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/server/**"]
  external_node_modules = ["@supabase/supabase-js", "node-fetch"]

[functions.crawler]
  included_files = ["src/server/**"]

[functions.scheduledCrawler]
  schedule = "0 */6 * * *"
  included_files = ["src/server/**"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  NODE_VERSION = "18"

# Don't include environment variables here - they should be set in Netlify dashboard
[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 5173
  publish = "dist" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://rqcowtehcygzmqgkvfiq.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*; font-src 'self' data: https://fonts.gstatic.com https://*; img-src 'self' data: https: http: blob:; connect-src 'self' https://rqcowtehcygzmqgkvfiq.supabase.co https://*.venturebeat.com https://*.wp.com https://fonts.googleapis.com https://fonts.gstatic.com https://*.techcrunch.com https://*.microsoft.com https://*.infor.com https://dam.infor.com https://*.oracle.com https://*; frame-src 'self' https://*;" 