[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions.crawler]
  schedule = "0 */6 * * *"

[build.environment]
  NODE_VERSION = "18"

# Don't include environment variables here - they should be set in Netlify dashboard
[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 5173
  publish = "dist" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://rqcowtehcygzmqgkvfiq.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https://*.venturebeat.com https://*.wp.com https://*.gettyimages.com https://venturebeat.com https://www.venturebeat.com https://*.techcrunch.com https://techcrunch.com https://*.microsoft.com https://www.microsoft.com https://*.infor.com https://dam.infor.com https://*.oracle.com https://www.oracle.com; connect-src 'self' https://rqcowtehcygzmqgkvfiq.supabase.co https://*.venturebeat.com https://*.wp.com https://fonts.googleapis.com https://fonts.gstatic.com https://*.techcrunch.com https://*.microsoft.com https://*.infor.com https://dam.infor.com https://*.oracle.com" 